version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(admin|migrate)
  script: admin.app
  login: admin

- url: /(send|message|promo)
  script: lljbot.app
  login: admin

- url: /.*
  script: lljbot.app