runtime: python312
app_engine_apis: true

handlers:
# - url: /(admin|migrate)
#   script: auto
#   login: admin

- url: /(send|message|promo|mass|photo|verify)
  script: auto
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: auto
