version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /send
  script: lljbot.app
  login: admin

- url: /retry
  script: lljbot.app
  login: admin

- url: /admin
  script: admin.app
  login: admin

- url: /.*
  script: lljbot.app