version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin
  script: admin.app
  login: admin

- url: /(send|retry|message|promo|migrate)
  script: lljbot.app
  login: admin

- url: /.*
  script: lljbot.app